language: python
addons:
    apt:
      packages:
        - cmake
      sources:
        - kalakris-cmake
python:
  - "2.7"
install:
  - sudo apt-get install -qq gcc-avr binutils-avr avr-libc
  - sudo apt-get install -y gcc-arm-none-eabi
  ############################################################################
  # Install a recent CMake
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew install cmake
    fi

script:
  - python build.py -t
notifications:
  email: false