language: cpp
os: osx
before_install:
  - echo -e "machine github.com\n  login $CI_TOKEN" >> ~/.netrc
install:
  - brew install avr-binutils avr-gcc avr-libc arm-none-eabi-gcc cmake
before_script:
  - cd ${TRAVIS_BUILD_DIR}
script:
  - python build.py -t
notifications:
  email: false