language: python
services:
  - docker
python:
  - "2.7"
before_install:
  - docker build coolya/gcc-avr
  - docker run coolya/gcc-avr
  - echo -e "machine github.com\n  login $CI_TOKEN" >> ~/.netrc
install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
  - docker exec coolya/gcc-avr python ./build.py -t
  - sudo apt-get install -y gcc-arm-none-eabi
before_script:
  - cd ${TRAVIS_BUILD_DIR}
script:
  - python build.py -t
notifications:
  email: false