language: python
python:
  - "2.7"
before_install:
  - echo -e "machine github.com\n  login $CI_TOKEN" >> ~/.netrc
  - docker build --name codal-build  --build-arg AUTH_TOKEN=$CI_TOKEN -t https://github.com/lancaster-university/codal-docker.git .
script:
  - docker run -it codal-build /bin/bash python build.py -t
notifications:
  email: false