# Ubuntu run on every commit, PR, and once a day
name: Build CODAL (Ubuntu)

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
  schedule:
    # Runs every working day at 8 am
    - cron: '0 8 * * 1-5'

jobs:
  build-py-script:
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-16.04]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: build.py ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install toolchain (Ubuntu)
        if: runner.os == 'Linux'
        run: sh ./.github/workflows/scripts/install-toolchain-ubuntu.sh
      - name: Check Versions
        run: |
          arm-none-eabi-gcc --version
          cmake --version
          ninja --version
          srec_cat --version
      - name: Configure git to access repos via GH Token URL
        run: git config --global url."https://x-access-token:${{ secrets.GH_TOKEN_MICROBIT_MACHINE }}@github".insteadOf https://github
      - name: Build using build.py
        run: python build.py
      - name: Upload hex file
        uses: actions/upload-artifact@v1
        with:
          name: hex-build-py-${{ matrix.os }}
          path: MICROBIT.hex

  build-yotta:
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-16.04]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: Yotta ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install toolchain (Ubuntu)
        if: runner.os == 'Linux'
        run: sh ./.github/workflows/scripts/install-toolchain-ubuntu.sh
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install Yotta
        run: python -m pip install yotta
      - name: Check Versions
        run: |
          arm-none-eabi-gcc --version
          cmake --version
          ninja --version
          srec_cat --version
          python --version
          python -m pip --version
          yotta --version
      - name: Configure git to access repos via GH Token URL
        run: |
          git config --global url."https://x-access-token:${{ secrets.GH_TOKEN_MICROBIT_MACHINE }}@github".insteadOf https://github
          git config --global url."https://x-access-token:${{ secrets.GH_TOKEN_MICROBIT_MACHINE }}@github.com/".insteadOf git@github.com:
      - name: Clone codal-yotta-target inside a yotta_targets folder
        run: git clone --recurse-submodules https://github.com/microbit-foundation/codal-yotta-target.git yotta_targets/codal-yotta-target
      - name: Set Yotta target
        run: yotta target codal-yotta-target
      - name: Build with Yotta
        run: yotta build
      - name: Upload hex file
        uses: actions/upload-artifact@v1
        with:
          name: hex-yotta-${{ matrix.os }}
          path: codal.hex
